# -*- coding: utf-8 -*-
"""Fifa_FootWeight_Visualization_BoxPlot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g_4YUv8r-dQurDtVm8EhwpSOKLRYQA9R
"""

import matplotlib.pyplot as plt

import numpy as np

import pandas as pd

"""**Load FIFA Data**"""

import pandas as pd
gas=pd.read_csv('/content/gas_prices.csv')
fifa=pd.read_csv('/content/fifa_data.csv')

fifa.head()

fifa['Preferred Foot']

"""**Histogram**

"""

bins=[40,50,60,70,80,90,100]
plt.hist(fifa.Overall,bins=bins, color='red')
plt.xticks(bins)
plt.ylabel('Number of Players')
plt.xlabel('Skill Level')
plt.title("Distribution of Player Skills in FIFA 2018")

plt.show()

for col in fifa:
  print(col)

"""**pie** **CHart**

bold text
"""

left=fifa.loc[fifa['Preferred Foot'] == 'Left'].count()[0]
right=fifa.loc[fifa['Preferred Foot'] == 'Right'].count()[0]

left

right

labels=['left','right']

plt.pie([left, right], labels=labels,autopct='%.2f %%')
plt.title("Foot preferred of Fifa Players")

fifa['Weight']

fifa.weight=[ x.strip('lbs') if type(x)==str else x for x in fifa.Weight]

fifa.Weight=[int(x.strip('lbs')) if type(x)==str else x for x in fifa.Weight]

fifa.Weight

fifa.Weight[41]

light=fifa.loc[fifa.Weight < 125].count()[0]
light_medium=fifa.loc[(fifa.Weight >=125) & (fifa.Weight < 150)].count()[0]

light

light_medium=fifa.loc[(fifa.Weight>=125) & (fifa.Weight<150)]

light_medium

medium=fifa.loc[(fifa.Weight >=150) & (fifa.Weight < 175)].count()[0]
medium_heavy=fifa[(fifa.Weight>=175) & fifa.Weight<200].count()[0]
heavy=fifa[(fifa.Weight>=200)].count()[0]

medium

weights=[light, light_medium,medium,medium_heavy,heavy]

labels=['under_125','125-150','150-175','175-200','over 200']
plt.style.use('ggplot')
explode=(.4,0.2,0,0,0.4)
plt.figure(1,figsize=(5,8))
plt.pie(weights,labels=labels,autopct='% .2f %%',pctdistance=0.9, explode=explode)
plt.title('Foot Weight Distribution in Fifa Player (in lbs) ')
plt.savefig('Fifa_Foot_Weight_Pie.png')
plt.legend()
plt.show()

"""**Box** **Plot**"""

plt.style.use('default')
plt.figure(figsize=(5,8))
barcelona=fifa.loc[fifa.Club=='FC Barcelona']['Overall']
madrid=fifa.loc[fifa.Club=='Real Madrid']['Overall']
rev=fifa.loc[fifa.Club== 'New England Revolution']['Overall']
labels=['FC Barcelona', 'Real Madrid ', 'NE England Revolution']
boxes=plt.boxplot([barcelona,madrid,rev], labels=labels, patch_artist=True, medianprops={'linewidth':2})
colors=['blue','green','red']
facecolors=['black','white','grey']
for box in boxes['boxes']:
  box.set(color=colors.pop(0), linewidth=2)
  box.set(facecolor=facecolors.pop(0))
plt.title("Professional Soccer Teams Comparision")
plt.ylabel('Fifa Over all Rating ')

plt.legend()
plt.savefig('Fifa_Boxplot_Player_Overall.png', dpi=300)
plt.show()



